from config.paths import (
    BASE_DIR,
    MODELS_DIR,
    LOGS_DIR,
    WHISPER_DIR,
    LLM_DIR,
    SUPERTONIC_DIR,
)
from config.whisper import WHISPER_MODEL_NAME, WHISPER_SAMPLE_RATE, WHISPER_DEVICE
from config.llm import ACTIVE_LLM_MODEL, GPU_LAYERS, CONTEXT_SIZE, CPU_THREADS
from config.tts import (
    TTS_MODE,
    TTS_SERVER_BACKEND,
    SUPERTONIC_VOICE,
    SUPERTONIC_LANGUAGE,
    SUPERTONIC_STEPS,
    SUPERTONIC_SPEED,
)
from config.vad import (
    RECORD_SAMPLE_RATE,
    SILENCE_THRESHOLD,
    SILENCE_DURATION,
    MIN_SPEECH,
    ROLLING_WINDOW_SEC,
    ENERGY_THRESHOLD,
    MIN_SPEECH_SEC,
    PAUSE_SECONDS,
    MIN_AUDIO_SEC,
    NO_SPEECH_THRESHOLD,
    LOGPROB_THRESHOLD,
    TRANSCRIBE_EVERY,
    COMPRESSION_RATIO_THRESHOLD,
)
from config.server import SERVER_PORT, SERVER_HOST
from config.features import ENABLE_STT, ENABLE_TTS, SHOW_TEXT
from config.prompt import (
    # VOICE_SYSTEM_PROMPT,
    VOICE_MAX_TOKENS,
    VOICE_TEMPERATURE,
    VOICE_MAX_HISTORY_TURNS,
)
